/* Centros de acopio de ejemplo (semilla del servidor) */
module.exports = [
  {
    id: 'chacao',
    coords: { lat: 10.4979, lng: -66.8536 },
    name: 'Centro de Acopio Chacao',
    type: 'Alcaldía',
    status: 'verificado',
    distance: 1.2,
    estado: 'Miranda', municipio: 'Chacao', parroquia: 'Chacao',
    address: 'Av. Francisco de Miranda, Centro Comercial El Parque, PB',
    reference: 'Al lado de la estación del Metro Chacao',
    responsable: 'María', responsableApellido: 'González', whatsapp: '0414-1234567',
    needs: [
      { key: 'agua', level: 'critica' },
      { key: 'gasas', level: 'critica' },
      { key: 'panales', level: 'alta' },
    ],
    accepts: ['fisico', 'pagomovil', 'cripto'],
    notAccepts: ['Medicinas vencidas', 'Comida vencida', 'Ropa en mal estado'],
    pagomovil: { banco: 'Banesco (0134)', telefono: '0414-1234567', cedula: 'V-12.345.678', titular: 'Asoc. Civil Chacao Solidario', concepto: 'Donación AyudaVE' },
    transferencia: { banco: 'Banesco', cuenta: '0134-0000-00-0000000000', titular: 'Asoc. Civil Chacao Solidario', cedula: 'J-40123456-7' },
    crypto: [
      { red: 'USDT TRC20', wallet: 'TXk9aH4mC2pQ7rL8vN3sD6fG1bW5eY0uJq' },
      { red: 'USDC Polygon', wallet: '0x9A4f2b7C1e8D3a5B6c9E0f1A2b3C4d5E6f7A8b9C' },
    ],
    horario: 'Lun a Sáb, 8:00 AM - 6:00 PM',
    inventory: [
      { key: 'agua', label: 'Agua (botellones)', qty: 24 },
      { key: 'comida', label: 'Cajas de comida', qty: 60 },
      { key: 'panales', label: 'Paquetes de pañales', qty: 8 },
    ],
    stats: { reportadas: 18, confirmadas: 12, entregadas: 9, voluntarios: 14 },
    updates: [
      { type: 'urgente', text: 'Urgente: necesitamos gasas y pañales para mañana.', date: 'Hace 1 h' },
      { type: 'recibido', text: 'Hoy recibimos 40 cajas de agua. ¡Gracias!', date: 'Hace 4 h' },
      { type: 'entrega', text: 'Entregamos comida a 20 familias en La Guaira.', date: 'Ayer' },
    ],
  },
  {
    id: 'santa-eduvigis',
    coords: { lat: 10.4930, lng: -66.8320 },
    name: 'Centro de Acopio Santa Eduvigis',
    type: 'Iglesia',
    status: 'verificado-operativo',
    distance: 2.1,
    estado: 'Miranda', municipio: 'Sucre', parroquia: 'Leoncio Martínez',
    address: 'Calle Santa Ana, Parroquia Santa Eduvigis',
    reference: 'Frente a la plaza',
    responsable: 'José', responsableApellido: 'Pérez', whatsapp: '0424-7654321',
    needs: [
      { key: 'comida', level: 'alta' },
      { key: 'powerbanks', level: 'media' },
      { key: 'voluntarios', level: 'alta' },
    ],
    accepts: ['fisico', 'pagomovil', 'cripto', 'voluntarios'],
    notAccepts: ['Efectivo físico sin registro', 'Comida vencida'],
    pagomovil: { banco: 'Mercantil (0105)', telefono: '0424-7654321', cedula: 'V-9.876.543', titular: 'Parroquia Santa Eduvigis', concepto: 'Ayuda humanitaria' },
    transferencia: { banco: 'Mercantil', cuenta: '0105-0000-00-0000000000', titular: 'Parroquia Santa Eduvigis', cedula: 'J-30987654-3' },
    crypto: [{ red: 'USDT TRC20', wallet: 'TQ2mB8nP4xR1cV6tL9sK3dF7gH5jW0eY2u' }],
    horario: 'Todos los días, 9:00 AM - 8:00 PM',
    inventory: [
      { key: 'agua', label: 'Agua (cajas)', qty: 12 },
      { key: 'comida', label: 'Cajas de comida', qty: 5 },
    ],
    stats: { reportadas: 9, confirmadas: 7, entregadas: 4, voluntarios: 6 },
    updates: [
      { type: 'urgente', text: 'Necesitamos 3 voluntarios para clasificar comida hoy.', date: 'Hace 2 h' },
      { type: 'aviso', text: 'Mañana recibimos donaciones desde las 9 AM.', date: 'Hace 6 h' },
    ],
  },
  {
    id: 'santa-monica',
    coords: { lat: 10.4810, lng: -66.8730 },
    name: 'Centro de Acopio Santa Mónica',
    type: 'Universidad',
    status: 'verificado',
    distance: 1.5,
    estado: 'Distrito Capital', municipio: 'Libertador', parroquia: 'Santa Mónica',
    address: 'Av. Principal de Santa Mónica, Edif. Comunitario',
    reference: 'Cerca de la UCV',
    responsable: 'Ana', responsableApellido: 'Rodríguez', whatsapp: '0412-1112233',
    needs: [
      { key: 'comida', level: 'alta' },
      { key: 'voluntarios', level: 'critica' },
    ],
    accepts: ['fisico', 'pagomovil', 'voluntarios'],
    notAccepts: ['Ropa en mal estado'],
    pagomovil: { banco: 'Banco de Venezuela (0102)', telefono: '0412-1112233', cedula: 'V-15.222.333', titular: 'Voluntariado Santa Mónica', concepto: 'Donación' },
    transferencia: { banco: 'Banco de Venezuela', cuenta: '0102-0000-00-0000000000', titular: 'Voluntariado Santa Mónica', cedula: 'V-15.222.333' },
    crypto: [],
    horario: 'Lun a Vie, 1:00 PM - 7:00 PM',
    inventory: [{ key: 'comida', label: 'Cajas de comida', qty: 30 }],
    stats: { reportadas: 5, confirmadas: 3, entregadas: 2, voluntarios: 3 },
    updates: [
      { type: 'urgente', text: 'Necesitamos 3 voluntarios para clasificar comida, 2 PM - 6 PM.', date: 'Hace 30 min' },
    ],
    tasks: [
      { id: 't1', title: 'Clasificar comida', needLabel: 'Necesita 3 voluntarios para clasificar comida', horario: '2 PM - 6 PM', skill: 'clasificar' },
    ],
  },
  {
    id: 'altamira',
    coords: { lat: 10.5012, lng: -66.8470 },
    name: 'Centro de Acopio Altamira',
    type: 'Fundación',
    status: 'verificado-operativo',
    distance: 2.8,
    estado: 'Miranda', municipio: 'Chacao', parroquia: 'Chacao',
    address: 'Av. Luis Roche, Altamira',
    reference: 'Plaza Altamira',
    responsable: 'Carlos', responsableApellido: 'Mendoza', whatsapp: '0414-9998877',
    needs: [
      { key: 'agua', level: 'alta' },
      { key: 'transporte', level: 'critica' },
    ],
    accepts: ['fisico', 'transporte', 'pagomovil', 'cripto'],
    notAccepts: ['Medicinas vencidas'],
    pagomovil: { banco: 'BBVA Provincial (0108)', telefono: '0414-9998877', cedula: 'V-11.444.555', titular: 'Fundación Altamira Ayuda', concepto: 'Donación AyudaVE' },
    transferencia: { banco: 'BBVA Provincial', cuenta: '0108-0000-00-0000000000', titular: 'Fundación Altamira Ayuda', cedula: 'J-41555666-7' },
    crypto: [{ red: 'USDT Polygon', wallet: '0x1B2c3D4e5F6a7B8c9D0e1F2a3B4c5D6e7F8a9B0c' }],
    horario: 'Lun a Sáb, 8:00 AM - 5:00 PM',
    inventory: [{ key: 'agua', label: 'Agua (botellones)', qty: 40 }],
    stats: { reportadas: 11, confirmadas: 8, entregadas: 6, voluntarios: 9 },
    updates: [
      { type: 'urgente', text: 'Necesitamos transporte para llevar agua hoy.', date: 'Hace 1 h' },
    ],
    tasks: [
      { id: 't2', title: 'Transporte de agua', needLabel: 'Necesita transporte para llevar agua', horario: 'Hoy', skill: 'transporte' },
    ],
  },
  {
    id: 'los-palos-grandes',
    coords: { lat: 10.5035, lng: -66.8425 },
    name: 'Centro de Acopio Los Palos Grandes',
    type: 'Comunidad',
    status: 'verificado-operativo',
    distance: 3.4,
    estado: 'Miranda', municipio: 'Chacao', parroquia: 'Chacao',
    address: '4ta Av. de Los Palos Grandes',
    reference: 'Cerca del bulevar',
    responsable: 'Luisa', responsableApellido: 'Castro', whatsapp: '0426-3334455',
    needs: [
      { key: 'gasas', level: 'critica' },
      { key: 'panales', level: 'alta' },
      { key: 'voluntarios', level: 'media' },
    ],
    accepts: ['fisico', 'pagomovil', 'cripto', 'voluntarios', 'transporte'],
    notAccepts: ['Comida vencida', 'Efectivo físico sin registro'],
    pagomovil: { banco: 'Banesco (0134)', telefono: '0426-3334455', cedula: 'V-13.666.777', titular: 'Consejo Comunal Los Palos Grandes', concepto: 'Donación' },
    transferencia: { banco: 'Banesco', cuenta: '0134-0000-00-0000000000', titular: 'Consejo Comunal Los Palos Grandes', cedula: 'J-42777888-9' },
    crypto: [
      { red: 'USDT TRC20', wallet: 'TP7kL2mN9xR4cV1tB6sJ8dF3gH5wQ0eY7u' },
      { red: 'USDC Base', wallet: '0x7F8e9D0c1B2a3F4e5D6c7B8a9F0e1D2c3B4a5F6e' },
    ],
    horario: 'Lun a Dom, 7:00 AM - 7:00 PM',
    inventory: [
      { key: 'agua', label: 'Agua (botellones)', qty: 18 },
      { key: 'panales', label: 'Paquetes de pañales', qty: 22 },
    ],
    stats: { reportadas: 13, confirmadas: 10, entregadas: 7, voluntarios: 11 },
    updates: [
      { type: 'recibido', text: 'Hoy recibimos 40 cajas de agua.', date: 'Hace 3 h' },
      { type: 'cierre', text: 'Cerramos hoy a las 7 PM. Mañana abrimos 7 AM.', date: 'Hace 5 h' },
    ],
  },
];
